### ISSUE TITLE
因为Context问题导致程序崩溃

### ISSUE THREAD

**Issue by EricSun-Android** [Blincheng/EToast2#2]
前提：ToastUtil不是单例模式。activity中弹出吐司，然后退出activity，会导致程序崩溃。
ProfitActivity has leaked window android.widget.LinearLayout{44df6818 V.E..... ........ 0,0-438,132} that was originally added here
at android.view.ViewRootImpl.(ViewRootImpl.java:381)
at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:258)
at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
at com.mic.etoast2.EToast2.show(EToast2.java:84)
utils.ToastUtlis.showShort(ToastUtlis.java:49)

点到报错定位的地方， public void show() {
if(oldToast == null) {
oldToast = this.toast;
this.manger.addView(contentView, this.params);
timer = new Timer();
} else {
timer.cancel();
oldToast.setText(this.text);
}

    timer = new Timer();
    timer.schedule(new TimerTask() {
        public void run() {
            EToast2.handler.sendEmptyMessage(1);
        }
    }, this.time.longValue());
}
在this.manager.addView 那行

**Comment by EricSun-Android** [comment]
应该是Context的问题，activity关闭以后，以activity.this为context 的上下文已经消失，这时候再往activity的window上添加view 导致崩溃。 不知道如果加个非空判断是不是能避免这个问题？
我现在的解决方案是：用全局Context，不会导致程序崩溃了。  但是问题就是activity弹出吐司以后，关闭activity吐司还会显示一小段时间，因为用的是全局的context。

**Comment by Blincheng** [comment]
上面的问题我看了一下，的确，当弹出Toast后快速关闭当前Activity会导致这个问题，主要原因是removeView异常导致的，对于这种情况，就只能暂时trycatch了，因为EToast没有和当前的Context绑定生命周期。其实如果真的想这么做，可以参考博文2的第一种实现方式，添加一个空的fragment来做生命周期绑定

**Comment by Blincheng** [comment]
非常感谢指出
