### ISSUE TITLE
可以跳转Activity的时候像系统Toast一样显示，不会因为跳转ActivityToast就马上关闭显示

### ISSUE THREAD

**Issue by wvisible** [Blincheng/EToast2#4]
遇到问题如上，当我跳转一个Activity的时候，toast马上就关闭了，系统Toast不会马上关闭，有没有好的方法

**Comment by Blincheng** [comment]
对的，因为Activity被关闭，Toast自然消失。可以这么做，弹出Toast后，延迟2秒再跳转

**Comment by wvisible** [comment]
好的 ，我试试，谢谢
